name: sat_mapstore_system

services:
  postgres:
    build:
      context: "./docker/postgres/"
    image: geosolutions-mapstore/postgis
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERPASS}
      POSTGRES_DB: ${POSTGRES_DB}
      GEOSTORE_DB_USER: ${GEOSTORE_DB_USER}
      GEOSTORE_DB_PASS: ${GEOSTORE_DB_PASS}
      GEOSTORE_DB_SCHEMA: ${GEOSTORE_DB_SCHEMA}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    networks:
      - mapstore-network
    profiles:
      - mapstore

  geoserver:
    image: kartoza/geoserver:2.21.0
    container_name: geoserver
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - geoserver_uploads:/mnt/uploads
    depends_on:
      - postgres
    networks:
      - mapstore-network
    profiles:
      - mapstore

  mapstore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OVR: geostore-datasource-ovr-postgres.properties
        MAPSTORE_WEBAPP_SRC: "./product/target/mapstore.war"
    container_name: mapstore
    command:
      - sh
      - -lc
      - |
        sed -i "s|GEOSTORE_USER_PLACEHOLDER|$${GEOSTORE_DB_USER}|" /usr/local/tomcat/conf/geostore-datasource-ovr-postgres.properties
        sed -i "s|GEOSTORE_PASS_PLACEHOLDER|$${GEOSTORE_DB_PASS}|" /usr/local/tomcat/conf/geostore-datasource-ovr-postgres.properties
        exec catalina.sh run
    environment:
      JAVA_OPTS: >-
        -DPRINT_BASE_URL=pdf
        -Ddatadir.location=/usr/local/tomcat/datadir
        -Dgeostore-ovr=file:///usr/local/tomcat/conf/geostore-datasource-ovr-postgres.properties
      GEOSTORE_DB_USER: ${GEOSTORE_DB_USER}
      GEOSTORE_DB_PASS: ${GEOSTORE_DB_PASS}
    depends_on:
      postgres:
        condition: service_healthy
      geoserver:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - mapstore_data:/usr/local/tomcat/datadir
      - ./docker/proxy.properties:/usr/local/tomcat/datadir/proxy.properties:ro
    networks:
      - mapstore-network
    profiles:
      - mapstore

  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./docker/mapstore.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80"
    depends_on:
      - mapstore
    networks:
      - mapstore-network
    profiles:
      - mapstore

networks:
  sat_network:
    driver: bridge
  mapstore-network:
    driver: bridge

volumes:
  sat_data:
    driver: local
  sat_logs:
    driver: local
  pg_data:
  geoserver_data:
  geoserver_uploads:
  mapstore_data:
